### ISSUE TITLE
在子页面点击主页链接会跳转到当前页面的category的主页上，而不是网站主页。

### ISSUE THREAD

**Issue by huangfeidian** [mawenbao/niu-x2-sidebar#10]
在使用中遇到这种情况，不知如何解决。

**Comment by mawenbao** [comment]
你好，首先确定下你是否修改过`templates/header.html`文件
```
cd niu-x2-sidebar
git status
```

如果没有修改，运行下面的命令，把输出贴一下。
```
git log HEAD | head -n 1
```

**Comment by huangfeidian** [comment]
哇，你回的好勤快。我没有修改 （其实是压根不知道怎么改）
第二个命令输出如下：commit a6831efd380d84bd25aadfd227f6bc818d15a645

**Comment by mawenbao** [comment]
额，刚才就在github上转悠。。。

版本似乎是没问题的，你能否把有问题的网页贴一下，我去看看。

**Comment by huangfeidian** [comment]
就是我的个人github page

**Comment by mawenbao** [comment]
我围观了一下，你用的应该是niu-x2-sidebar的一个[fork](https://github.com/FinalTheory/pelican-theme)，建议你去那里发个issue，因为我不太清楚那个同学做了啥改动。

**Comment by huangfeidian** [comment]
其实用你的也是一样的。另外还有一个issue，就是标题中有latex数学公式的时候提取目录功能无法正常工作。

**Comment by huangfeidian** [comment]
我在另外一台机器上用你的，则是压根不跳转，直接转回当前页面。home链接和作者链接都是如此。。。

**Comment by huangfeidian** [comment]
额，发现了一个更加诡异的问题。在ie下是会跳转到当前文章的category页面，而在firefox下则会跳转到当前页面。

**Comment by mawenbao** [comment]
我没有看那位同学具体修改了什么，不过他确实改了不少东西，包括latex公式，原本的niu-x2-sidebar是不支持的。

我用不同的浏览器看了下你的网站，确实会很诡异。猜测是js的兼容性问题，还是建议你去咨询下那位同学。

至于你说用了原始的niu-x2-sidebar根本不跳转，很可能是因为你没有在配置文件里设置`SITEURL`。

**Comment by huangfeidian** [comment]
加了siteurl之后，所有问题解决。看了一下，当前你的那个pull request 里面提到的问题跟我这个类似。
