### ISSUE TITLE
你站点的google搜索功能应该挂掉了

### ISSUE THREAD

**Issue by huiyadanli** [mawenbao/niu-x2-sidebar#12]
`header.html` 中
`http://google.com/cse` 修改为 `http://cse.google.com/cse` 就可以了

**Comment by mawenbao** [comment]
我这里https://google.com/cse会自动跳转到https://cse.google.com/cse。不过我还是改一下吧，多谢提醒。

**Comment by huiyadanli** [comment]
原来是我这边科学上网没有匹配 //google.com 形式的链接，开了全局代理以后，//google.com/cse 是能正常跳转的
