### ISSUE TITLE
关于iconmoon的选择

### ISSUE THREAD

**Issue by JeremyHe-cn** [mawenbao/niu-x2-sidebar#2]
我在写分类的时候
```
# original name: (display name, icon class)
NIUX2_CATEGORY_MAP = {
    "android": ("Android", "fa-android"),
    "hexo": ("Hexo", "fa-header")
}
```
我怎么知道当前主题里的iconmoon里有哪些图标呢，图标的class name名字是什么？
怎么样才可以使用fontawsome?我直接写fa fa-android好像没什么效果。

**Comment by zyxnero** [comment]
猜测fontawesome中的图标都支持吧，http://fortawesome.github.io/Font-Awesome/icons/，先看看这里，坐等@mawenbao解答

**Comment by JeremyHe-cn** [comment]
@zyxnero 目前我是修改了模版base.html,加入了
```
{% set font_awesome_loc = NIUX2_LIB_FONTAWESOME if NIUX2_LIB_FONTAWESOME else '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/' %}
<link rel="stylesheet" href="{{ font_awesome_loc }}/css/font-awesome.min.css">
```
然后在配置文件里加NIUX2_LIB_FONTAWESOME变量来解决的。

有可以@mawenbao 已经有方法了但是不知道。

**Comment by JeremyHe-cn** [comment]
@zyxnero 默认应该是不支持的，我试过直接使用"fa fa-android"，这个是fontawesome里的图标。
如果不用上面那个配置的话，是没办法显示的。

**Comment by mawenbao** [comment]
你好，如果你用的是master分支(`git checkout master`)，那么font-awesome的图标都是支持的。如果你用的是icomoon分支(`git checkout icomoon`)，可以到[这里](https://icomoon.io/app/#/select)自定义你的图标集，名字什么的都可以自己定义，最后下载生成的font文件并放到`niu-x2-sidebar/static/font-icons`目录里替换对应的文件即可。

当初考虑用icomoon代替font-awesome一是为了减小font文件体积，二是icomoon支持的图标更多。

**Comment by JeremyHe-cn** [comment]
嗯嗯好的，明白了
