### ISSUE TITLE
Found duplicated heading id

### ISSUE THREAD

**Issue by huangfeidian** [mawenbao/niu-x2-sidebar#7]
我非常喜欢你的这个工具，准备把我的wordpress迁移到pelican来。可是我在初步使用时发现，执行pelican content时一直出现warning found duplicated heading id 这个问题，这样导致右侧边栏的目录部分基本不可用。请问这个问题如何解决。 样例文档在此：http://pan.baidu.com/s/1c0GVXdu。 麻烦你了，我刚接触pelican和python。不甚感激！

**Comment by mawenbao** [comment]
你好，多谢支持。我这边用那个文档测试了下，没发现问题。

请确保用的是最新的插件

```
git submodule foreach git pull
```

如果还有问题，麻烦贴一下你的slugify函数，我用的是这个

```
import md5 
def my_slugify(value, sep):
    m = md5.md5(value.encode('UTF-8'))
    return m.digest().encode('hex')[:6]
MY_SLUGIFY_FUNC = my_slugify
```

**Comment by huangfeidian** [comment]
耶，能用了 ，非常感谢。
