### ISSUE TITLE
请问 niu-x2-siderbar 支持生成 RST 文件的 TOC 吗？

### ISSUE THREAD

**Issue by whypro** [mawenbao/niu-x2-sidebar#8]
这个主题非常棒。但是我遇到了一些问题。
我使用的是 rst 格式来写博客，但是生成 html 后侧边栏的 TOC 貌似无法正常生成。
请问 niu-x2-sidebar 支持生成 RST 文件的 TOC 吗？

我用的 Pelican 3.5， niu-x2-sidebar 是 master 分支。

**Comment by mawenbao** [comment]
你好，要生成侧边栏的TOC，得插件[extract_headings](https://github.com/mawenbao/extract_headings)，和文章的格式没有关系，标题都是从生成的html里提取的。

**Comment by mawenbao** [comment]
[extract_headings](https://github.com/mawenbao/extract_headings)插件已更新，问题应该解决了。
